export const TAG_LIST = [
    "All",
    "Music",
    "Mixes",
    "Lo-fi",
    "Live",
    "Background music",
    "Gaming",
    "Playlists",
    "News",
    "Deep House",
    "ASMR",
    "Personal finances",
    "Stock markets",
    "League of Legends",
    "Computer programming",
    "Manga",
    "Cars",
    "Recently uploaded",
    "Watched",
    "New to you",
]