const videos = [
    {
        title: "Duy nhất 14,15,18,19/9, cùng Pond’s nhận ưu đãi ngập tràn",
        duration: "0:30",
        thumbnail: "https://i4.ytimg.com/vi/DuxbP1jZKY4/0.jpg",
        channelAvatar: "https://yt3.ggpht.com/ytc/AOPolaS2pTry6JPK8eVuuhEa0nsEsYn_iOsfqwrrLsy-Uw=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Diệu Nhiên Lofi",
        view: "12K views",
        time: "23 hours ago",
        url: "https://www.youtube.com/watch?v=DuxbP1jZKY4",
    },
    {
        title: "Nhạc Lofi Chill Top Xu Hướng 2023 Triệu View ♬ Thay Tôi Yêu Cô Ấy, Ngày Em Đẹp Nhất, Hoa Cỏ Lau",
        duration: "3:12:12",
        thumbnail: "https://i.ytimg.com/vi/boNAbJH59nc/hqdefault.jpg?sqp=-oaymwE2COADEI4CSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhlIFsoSDAP&rs=AOn4CLA6zUHcNot2wMub2VPx0-xnq0HPHw",
        channelAvatar: "https://yt3.ggpht.com/NumUuCVrLj_Bl9Ykb9y43mrZMFCHPTNi5dUlwr0HWG8IEnBI1kPPkbLMOwXKNlPf2G8vj7ft=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Văn Tùng",
        view: "79K views",
        time: "1 month ago",
        url: "https://www.youtube.com/watch?v=boNAbJH59nc",
    },
    {
        title: "ĐỒNG ĐỘI QUYẾT TÂM ĐÁNH NHẤT XẠ TỨ NÔ XOAY QUANH XAYAH CỦA GUMAYUSI VÀ CÁI KẾT MÃN NHÃN",
        duration: "39:50",
        thumbnail: "https://i.ytimg.com/vi/FBZYmhKqBLo/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDmgYmCoXCtYXvJlWk7AUHTlruo1Q",
        channelAvatar: "https://yt3.ggpht.com/ytc/AOPolaToP-L_46VvBUtEtBEH7bI-U6jJxJ4-TjD2XAORtA=s68-c-k-c0x00ffffff-no-rj",
        channelName: "LOFI KEEP YOU SAFE",
        view: "19K views",
        time: "3 months ago",
        url: "https://www.youtube.com/watch?v=FBZYmhKqBLo",
    },
    {
        title: "Lofi Chill 🌼 Lofi Deep Focus 🌳 Study/Calm/Heal [ Lofi Hip Hop - Lofi Chill ]",
        duration: "11:55:56",
        thumbnail: "https://i.ytimg.com/vi/8DgnL-Vzh-U/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCVXVrHE6BkYMo0FEHGhcGq-W3u1Q",
        channelAvatar: "https://yt3.ggpht.com/XDY_UbfPTh8MaRSFAihPDdHnjwDR4Qwx7XHJYBpGNrrztOKqD2VTbmzy8gu9vaTOkHeBMuRqfUo=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Lá Diêu Bông",
        view: "146 views",
        time: "8 hours ago",
        url: "https://www.youtube.com/watch?v=8DgnL-Vzh-U",
    },
    {
        title: "Vì Ngày Em Đẹp Nhất Là Ngày Anh Mất Em... ♬ NGÀY EM ĐẸP NHẤT Lofi 💿 Nhạc Trẻ Lofi Hot TikTok 2023",
        duration: "1:24:06",
        thumbnail: "https://i.ytimg.com/vi/5SObXnjzV3U/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAl7jzgYvx8pwKTdxhw1_Krg8zeXw",
        channelAvatar: "https://yt3.ggpht.com/_U5dAlHS7y79ExVOxJdW0Za_vEiYuxKOpjHQeVB40W9UUAPeQZiMhoM3ZGu7dxrJA_7q4ZLD=s68-c-k-c0x00ffffff-no-rj",
        channelName: "TodayVylearns",
        view: "1.1K views",
        time: "1 year ago",
        url: "https://www.youtube.com/watch?v=5SObXnjzV3U",
    },
    {
        title: "4 cách xây dựng mối quan hệ cho người hướng nội (mà không phải "gồng" hướng ngoại)",
        duration: "16:17",
        thumbnail: "https://i.ytimg.com/vi/bGZ-HvwxhkY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA_aps6xUgqkzygF6yd0FbzScztrw",
        channelAvatar: "https://yt3.ggpht.com/Sp7u5kgZ-N77YqSaBgVZMehmRS0ETIS2uFGnsidHlG5kUwIezbA3Edt8WxeXQ7ksxs6C0gaz2qw=s68-c-k-c0x00ffffff-no-rj",
        channelName: "JavaScript Mastery",
        view: "1.2M views",
        time: "10 months ago",
        url: "https://www.youtube.com/watch?v=bGZ-HvwxhkY&t=16s",
    },
    {
        title: "Build and Deploy 4 Modern React Apps and Get Hired as a Frontend Developer | Full 10-Hour Course",
        duration: "9:44:47",
        thumbnail: "https://i.ytimg.com/vi/F627pKNUCVQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA634LHcd4wMTk4BVONJDYMzskQaA",
        channelAvatar: "https://yt3.ggpht.com/wg1TITEoPfxvBGfzuqWyt3bqm_qu35ZhMswUv3feetU3xNX_6wsAXZF40OlPIgY4TmqbqCmAZ1U=s68-c-k-c0x00ffffff-no-rj",
        channelName: "1981 Lofi",
        view: "75 views",
        time: "29 minutes ago",
        url: "https://www.youtube.com/watch?v=F627pKNUCVQ",
    },
    {
        title: "Nhạc Trẻ 8x9x - Những Bản Nhạc Lofi 8x9x Nhẹ Nhàng | Nhạc Lofi 8x9x Hay Nhất Đời Đầu",
        duration: "1:05:30",
        thumbnail: "https://i.ytimg.com/vi/yFbrthgTe5I/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAo-mYzlwgbreu0JBjarGqLrLh4eQ",
        channelAvatar: "https://yt3.ggpht.com/T5j50juJYvvOma7fWbbiQ0D5Qjq5Z4h1xlArH4GxfmlbNQjUSUlPsfRS8D4unVeH47AwFzU3Hw=s68-c-k-c0x00ffffff-no-rj",
        channelName: "SHINPHAMM",
        view: "33K views",
        time: "9 days ago",
        url: "https://www.youtube.com/watch?v=yFbrthgTe5I",
    },
    {
        title: "Quay trở lại Nhật Bản 🇯🇵 // Một bước ngoặt mới // 18 tuổi lần nữa | Hello Japan | SHINPHAMM",
        duration: "9:40",
        thumbnail: "https://i.ytimg.com/vi/xkK2fC_891M/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC3pQJ_Sg9ru4wwBLIMlfOCj4MowQ",
        channelAvatar: "https://yt3.ggpht.com/ytc/AOPolaQK9qa-GMaYbdHTL4tS3w418XssP06aRsdNIGiUvQ=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Relaxing Ghibli Piano",
        view: "21K views",
        time: "2 weeks ago",
        url: "https://www.youtube.com/watch?v=xkK2fC_891M",
    },
    {
        title: "[Ghibli Piano Collection] Relaxing piano music 🌊 Studying, coffee, reading, healing 🎧 Ghibli Music",
        duration: "3:21:37",
        thumbnail: "https://i.ytimg.com/vi/CRCEU1Rec7M/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBRUyKWiRGwiejdlCB4RRWrUKaLHQ",
        channelAvatar: "https://yt3.ggpht.com/cyMxBfX2cRFNwEK-UdKXKp7tqZgnAOj-ji_ZcU9fcYwHax0kHrn9wZYg717EiWZwvlSHx52PXFU=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Trạm Xăng Số 7",
        view: "200 views",
        time: "6 hours ago",
        url: "https://www.youtube.com/watch?v=CRCEU1Rec7M",
    },
    {
        title: "Hí hửng m.u.a ghế bệt tựa lưng và cái kết | Quân Quân đây nè",
        duration: "1:01:31",
        thumbnail: "https://i.ytimg.com/vi/lfPA0nC1xbc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAYHUMWvMhHrzyj3AUp_oXG-nq0Ow",
        channelAvatar: "https://yt3.ggpht.com/qq9nWTfl8AIOptk31-YzPbv9XvG3fJSrg2jHWR6EuN8azmNr0xjXSLJ3mJaDND3n54jOaXhx=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Tài chính & Kinh doanh",
        view: "20K views",
        time: "Streamed 1 day ago",
        url: "https://www.youtube.com/watch?v=lfPA0nC1xbc",
    },
    {
        title: "1 mét 48 khi giận",
        duration: "28:58",
        thumbnail: "https://i.ytimg.com/vi/aEkssL21_B4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAGvW7AfTxw1DWEUO-B3WEImLz_pQ",
        channelAvatar: "https://yt3.ggpht.com/ytc/AOPolaRgf1QIHdsE7MXZBg0S5s5Qinz273s90Iuy_ycK=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Min Xinh",
        view: "24K views",
        time: "8 hours ago",
        url: "https://www.youtube.com/watch?v=aEkssL21_B4",
    },
    {
        title: "She traveled to surprise her long distance boyfriend ❤️",
        duration: "1:21:01",
        thumbnail: "https://i.ytimg.com/vi/yKYIrNgTLOA/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC-foNFtonkxmeZMUQKy6Z0Jeiqzg",
        channelAvatar: "https://yt3.ggpht.com/7QgQySkuThMtiuVii_aAB4tW5y9phjcp7ZFSxeCvvfcjHxfTfhGRMLnNWYASoMzx3iNya01J_A=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Ephemeral Rift",
        view: "732K views",
        time: "9 months ago",
        url: "https://www.youtube.com/watch?v=yKYIrNgTLOA",
    },
    {
        title: "Cậu bé 2k1 Phá kỷ lục chống đẩy thế giới 30s #shorts",
        duration: "3:10:22",
        thumbnail: "https://i.ytimg.com/vi/NKfrh1XlidM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDv0nwx2Rjx-XUZZCznSZvQN0LgFw",
        channelAvatar: "https://yt3.ggpht.com/eOGjfkT1hRwxea4XqwQHfC5ynRRS2G5RXsOTl1grPy2a1EKNCWVj7sZD_zWP4gnEJtxkOzt5Dw=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Levi",
        view: "65K views",
        time: "2 months ago",
        url: "https://www.youtube.com/watch?v=NKfrh1XlidM",
    },
    {
        title: "Thế là cả nước biết 🌚 #beatnow #beatnews #beatnetwork #beatvn",
        duration: "9:47",
        thumbnail: "https://i.ytimg.com/vi/4QUziibVcAA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAeCv4yuVYp6Ro6sLC1z_x0FL6TWg",
        channelAvatar: "https://yt3.ggpht.com/4ffrJrze6zBmxEfzUhR3TqYXBHWU_O6sii9jILfUdMbd8HhBAtk7CYeBEM-fp_S6RYu81Szsnw=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Em Suy",
        view: "",
        time: "29 minutes ago",
        url: "https://www.youtube.com/watch?v=4QUziibVcAA",
    },
    {
        title: "Ballad Nhẹ Nhàng - Nhạc Ballad Nhẹ Nhàng - Nhac chill nhe nhang hay nhat",
        duration: "1:22:36",
        thumbnail: "https://i.ytimg.com/vi/FWMqqbxUqyY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCBdZ4rtykfE4875UdxdOJZxfPsaA",
        channelAvatar: "https://yt3.ggpht.com/xEtlQdGKCmBftZzMCjTXXmzKRBkJq0JsluvpzRixJElhjKsfqJCbNWlf4oHyeosJZyKN-v7fmw=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Thế Giới Cổ Đại",
        view: "216K views",
        time: "10 days ago",
        url: "https://www.youtube.com/watch?v=FWMqqbxUqyY",
    },
    {
        title: "Sự thay đổi của các phân khúc bất động sản sau sự cố chung cư tại Hà Nội | ĐTDT 15/9/2023",
        duration: "20:03",
        thumbnail: "https://i.ytimg.com/vi/C2oDdIIzVME/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBTNnW3L-i-3x1GnoQmbnDvUmOnSg",
        channelAvatar: "https://yt3.ggpht.com/46yhoCfO9c0FR8Kzysib73yudVz2oj9HXwUcv6hwaFm5gab7_NsjxXvoZeRpoRojsYIFeo5NhQ=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Yang interior [양인테리어]",
        view: "3.2M views",
        time: "1 year ago",
        url: "https://www.youtube.com/watch?v=C2oDdIIzVME",
    },
    {
        title: "EDM TikTok Hay 2023 ♫ BXH Nhạc Trẻ Remix Hay Nhất Hiện Nay - Top 15 Bản EDM TikTok Hot Nhất 2023",
        duration: "6:34",
        thumbnail: "https://i.ytimg.com/vi/KvSd_fU33Dg/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCV0gloIPeNgI6s17jFJUBV41xxdA",
        channelAvatar: "https://yt3.ggpht.com/FRRozcxc_voC5DRfqvMqdIJO8550iR7cAiD5_Cahv2YWhKARYqHOxf5bs_E05RVOI93pWuMeEg=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Muse Việt Nam",
        view: "263K views",
        time: "12 days ago",
        url: "https://www.youtube.com/watch?v=KvSd_fU33Dg",
    },
    {
        title: "ASMER",
        duration: "24:08",
        thumbnail: "https://i.ytimg.com/vi/jbYtiwYa034/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB2L2bA8W1YlbAfblm-frVkiNd7ag",
        channelAvatar: "https://yt3.ggpht.com/fcGNMehIsr_C_WVq_L3DaBJMMkNr8MsIQ0skTiB-RIJaLDy1na1hbV6kjztaUp39VsHIWLgwCg=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Study With Me",
        view: "2.9K views",
        time: "18 hours ago",
        url: "https://www.youtube.com/watch?v=jbYtiwYa034",
    },
    {
        title: "TÌNH HÌNH ÔNG LÃO ĐÁNH CÁ LEVI SAU KHI ỔNG BỊ NHỮNG CHÚ CÁ VOI GÕ 2 CHÙY",
        duration: "1:21:58",
        thumbnail: "https://i.ytimg.com/vi/txYhaL8ZI-c/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhlIFUoRzAP&rs=AOn4CLAIVi3HSUa9LR6JHCINrEt40Jx7_A",
        channelAvatar: "https://yt3.ggpht.com/GC_gS5ENo2BYtr6zEh7U6mr8lg6bcGgPwc1gNPCY8MY9kNWdtf1bT3P1sJkwGnFfE87h0S8xBg=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Interlock",
        view: "37K views",
        time: "8 days ago",
        url: "https://www.youtube.com/watch?v=txYhaL8ZI-c",
    },
    {
        title: "Lần đầu thấy chuột đứng bằng đuôi 😱 #shorts",
        duration: "21:15",
        thumbnail: "https://i.ytimg.com/vi/ztjg_zggIYk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBAUysgAwk0rdo-t5akoT30LO3nUg",
        channelAvatar: "https://yt3.ggpht.com/7rxbnz1YVWCwvEC9gubHkglI5_NdTpaHfXE_HSsz6X-OZtjOQeQgH3bzzA201FbSm0W0guDf3Q=s68-c-k-c0x00ffffff-no-rj",
        channelName: "StudyMD",
        view: "169K views",
        time: "3 months ago",
        url: "https://www.youtube.com/watch?v=ztjg_zggIYk",
    },
    {
        title: "Review gậy tự vệ Hợp Pháp #shorts",
        duration: "2:00:26",
        thumbnail: "https://i.ytimg.com/vi/sz4t45bvKsw/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC3uhc-79cejqx7w0jJcPLp5yaRKw",
        channelAvatar: "https://yt3.ggpht.com/L0W93fDHgz9L_GGkmZvouFGNbbvHARFVhPsDVjK5NP-GqdUPPTDGwFQkUlDzh-WaOJmsx0DN3w=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Diệu Nhiên Lofi",
        view: "23K views",
        time: "1 month ago",
        url: "https://www.youtube.com/watch?v=sz4t45bvKsw",
    },
    {
        title: "Memes I found online part 6",
        duration: "2:03:47",
        thumbnail: "https://i.ytimg.com/vi/-GF-uf5efps/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBsRUZgFsrVhjbKnbUVtCS09Tjs_A",
        channelAvatar: "https://yt3.ggpht.com/NumUuCVrLj_Bl9Ykb9y43mrZMFCHPTNi5dUlwr0HWG8IEnBI1kPPkbLMOwXKNlPf2G8vj7ft=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Healing Compass",
        view: "44K views",
        time: "4 weeks ago",
        url: "https://www.youtube.com/watch?v=-GF-uf5efps",
    },
    {
        title: "cô dâu nói em không uống được đâu ạ, và cái kết cho đến khi nhỏ bạn thân lên chúc mừng. #Short",
        duration: "8:00:29",
        thumbnail: "https://i.ytimg.com/vi/cLfFQH0A9n4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBKPra_ouSaHTlZ-bgGgJB-yZlOXw",
        channelAvatar: "https://yt3.ggpht.com/RECzSRCx-XvXqOyhZz0s2OEWeJ-ZNKUJ4QWRLfTJ-ZacdAdXH4KMycrkQn89KKLdCyy73rrH=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Joma Tech",
        view: "1.3M views",
        time: "7 months ago",
        url: "https://www.youtube.com/watch?v=cLfFQH0A9n4",
    },
    {
        title: "She Couldn’t Believe It 😅",
        duration: "10:29",
        thumbnail: "https://i.ytimg.com/vi/lo1HRGl1CvE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC5OaC93IGDGH3Cw51yDnvmQp5oQg",
        channelAvatar: "https://yt3.ggpht.com/ytc/AOPolaRniwwqLAJRilIpDSvI4OHShn_1TOe7TN9kaQpZ=s68-c-k-c0x00ffffff-no-rj",
        channelName: "TC Zwag",
        view: "261K views",
        time: "2 days ago",
        url: "https://www.youtube.com/watch?v=lo1HRGl1CvE&t=12s",
    },
    {
        title: "Nhạc Lofi Chill | Vì ngày em đẹp nhất là ngày anh mất em...Ngày Em Đẹp Nhất | Lofi Gây Nghiện",
        duration: "35:46",
        thumbnail: "https://i.ytimg.com/vi/Gap81XiDSiI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAfWeB7QfNxuVsn2umSju9o8MM0dA",
        channelAvatar: "https://yt3.ggpht.com/ytc/AOPolaQI2Vq4HqNCcxnv_PgtDA23xawYJse-BZBGol2e=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Yukiniku",
        view: "831K views",
        time: "1 month ago",
        url: "https://www.youtube.com/watch?v=Gap81XiDSiI",
    },
    {
        title: "VÔ NGÃ - Khái Niệm Đỉnh Nhất Của Phật Giáo Sẽ Làm Bạn Nghi Ngờ Về Sự Tồn Tại Của Chính Mình",
        duration: "7:01",
        thumbnail: "https://i.ytimg.com/vi/KtNyEd3JhLI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA3DedH2bjpjLWnNru3bdk-F2fl2Q",
        channelAvatar: "https://yt3.ggpht.com/HAN-GaJ6RgcJBl37WxAKTzR27A7TWP3Hvnnz1pPypFmGkVazGOvwmSslfncDlfH0tc-d_0-l=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Minh Hodler",
        view: "12K views",
        time: "1 month ago",
        url: "https://www.youtube.com/watch?v=KtNyEd3JhLI",
    },
    {
        title: "Korean Best Water Underfloor Heating System",
        duration: "20:32",
        thumbnail: "https://i.ytimg.com/vi/ZnorSiCyNq4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD7NLbBcYwrsabF5jS7EOUG32Aq2w",
        channelAvatar: "https://yt3.ggpht.com/fsl2PyZa6AvdNzqo9wcN7Q3tfJ4ac8SLghjpUzqLIwUuF9F7J6-icY24z3CUWdC20v8veXpl=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Tokyo Lofi Healing",
        view: "37K views",
        time: "2 weeks ago",
        url: "https://www.youtube.com/watch?v=ZnorSiCyNq4",
    },
    {
        title: "100 điều tôi muốn làm trước khi trở thành xác sống - Tập 07 [Việt sub]",
        duration: "3:00:01",
        thumbnail: "https://i.ytimg.com/vi/y_mduWvzJEg/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARh_IDgoPzAP&rs=AOn4CLDSUWgjnAHkbQQo15AAz0gfGFn4Ew",
        channelAvatar: "https://yt3.ggpht.com/4UTktz2XJ18yNFgRoboUZL6wKLhGLdGZQX2kfk5NnFi-5vLXMW8LjOHRm-ZyTiKoGnLCVGYwMQ=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Bob Ross",
        view: "636K views",
        time: "11 months ago",
        url: "https://www.youtube.com/watch?v=y_mduWvzJEg",
    },
    {
        title: "Nhạc Baroque Giúp Bạn Tập Trung Học Tập Và Làm Việc - Nhạc Lofi Chill Không Lời Thư Giãn Nhẹ Nhàng",
        duration: "1:00:08",
        thumbnail: "https://i.ytimg.com/vi/P0MU6GRmJFk/hq720_live.jpg?sqp=CIDkmqgG-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA4FfUaDFF83ion5SVsvIf-OtRimg",
        channelAvatar: "https://yt3.ggpht.com/ZJGwKd4H-lsmPo6cZ2WJ7aaU6uRJYOAmj-MDIDy_Se0sUu3iM41hG3KXgVz690DeEPRqxaKx=s68-c-k-c0x00ffffff-no-rj",
        channelName: "New Lofi",
        view: "319K views",
        time: "3 months ago",
        url: "https://www.youtube.com/watch?v=P0MU6GRmJFk",
    },
    {
        title: "Kiếm tiền khó, vậy làm sao để bạn trẻ dư tiền - Doctor Housing | TIỀN THÂN Podcast Series 💵💵",
        duration: "2:00:01",
        thumbnail: "https://i.ytimg.com/vi/jOsqiOPe5Bg/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD4WNdfezQS9gwEOSTHf7JWpvzvig",
        channelAvatar: "https://yt3.ggpht.com/koj_G7X19zBjfuJXQ3NEhBNZE6DszU1n5TAbqDGUdbkOQCnx2fhXpObunBszZ6o7-iCx2YvS5H4=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Ghibli Music",
        view: "126K views",
        time: "6 days ago",
        url: "https://www.youtube.com/watch?v=jOsqiOPe5Bg",
    },
    {
        title: "Deep Focus Study Music 🎯/ 2-HOUR STUDY WITH ME / Pomodoro 45",
        duration: "17:00",
        thumbnail: "https://i.ytimg.com/vi/OdwR5JrkiVg/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDpS-427n5utENr8sFeddi8c20Q3w",
        channelAvatar: "https://yt3.ggpht.com/EOF0jeeDOONbg0uXRHH4GzpKSpgnR43MiaqjJyWYRngMRZcwZf40ErWoHxS8vpcLf37foxCKsg=s68-c-k-c0x00ffffff-no-rj",
        channelName: "Hieu Nguyen",
        view: "8.7M views",
        time: "3 years ago",
        url: "https://www.youtube.com/watch?v=OdwR5JrkiVg",
    },
    {
        title: "[Có lời] Thanh Xuân Của Người Anh Yêu... ♬ Nhạc Lofi Chill Top Xu Hướng 2023, Em Là Kẻ Đáng Thương",
        duration: "5:37",
        thumbnail: "https://i.ytimg.com/vi/HBkZgvMe2EE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBX_5NpRv8bMhpONwb9D6ZsabYcvg",
        channelAvatar: "https://yt3.ggpht.com/ytc/AOPolaTY9sxsNY6hucw-ST7_-bF2H5zRqTkOodr8lIOW3KM=s68-c-k-c0x00ffffff-no-rj",
        channelName: "yurisa",
        view: "5.9M views",
        time: "1 year ago",
        url: "https://www.youtube.com/watch?v=HBkZgvMe2EE",
    },
]

const shorts = [
    {
        title: "cameraman tâm sự về trải nghiệm làm nghề, ai thích hào quang rực rỡ thì nhào vô đây làm.#Shorts",
        thumbnail: "https://i.ytimg.com/vi/REVv6BaUpfQ/oar2.jpg?sqp=-oaymwEaCJUDENAFSFXyq4qpAwwIARUAAIhCcAHAAQY=&rs=AOn4CLBVA-l8BskL4qVgM4R7z5-YnVI3kw",
        view: "290K views",
    },
    {
        title: "The End 😂😅😂 #funny #shorts #viral #fails #mrsachu2.0",
        thumbnail: "https://i.ytimg.com/vi/E7tQXH_EkhQ/hq720.jpg?sqp=-oaymwEdCJUDENAFSFXyq4qpAw8IARUAAIhCcAHAAQbQAQE=&rs=AOn4CLCzkTD9p-6ANHnVwJk2j_tB31e7lg",
        view: "7.7M views",
    },
    {
        title: "Chất lỏng tự chảy | Bạn biết không",
        thumbnail: "https://i.ytimg.com/vi/I68KUaUDk9Y/oar2.jpg?sqp=-oaymwEaCJUDENAFSFXyq4qpAwwIARUAAIhCcAHAAQY=&rs=AOn4CLBv4uNAXVMIaqCbVFndU8IFCvvhcA",
        view: "1.4M views",
    },
    {
        title: "Wonder Woman and the Flash's weird running styles #shorts",
        thumbnail: "https://i.ytimg.com/vi/XBPqS_OvmrI/oar2.jpg?sqp=-oaymwEaCJUDENAFSFXyq4qpAwwIARUAAIhCcAHAAQY=&rs=AOn4CLBbCQiq2WyhQG9EJBT0N74hsSP8Lw",
        view: "1M views",
    },
    {
        title: "She Couldn't Believe Her Eyes! (🐒 vs🦞) #cute #pets #lifewithgaitlyn",
        thumbnail: "https://i.ytimg.com/vi/-xKXm2hmKjs/hq720.jpg?sqp=-oaymwEdCJUDENAFSFXyq4qpAw8IARUAAIhCcAHAAQbQAQE=&rs=AOn4CLANdGoSzz2ukrAqaowo_UslSyEsSg",
        view: "6.3M views",
    },
    {
        title: "bong bóng khổng lồ trên biển 💀",
        thumbnail: "https://i.ytimg.com/vi/04cwx5SiWyk/hq720.jpg?sqp=-oaymwEdCJUDENAFSFXyq4qpAw8IARUAAIhCcAHAAQbQAQE=&rs=AOn4CLCnlM6ra8rykIMBqi6RZDjl3BYndQ",
        view: "1.5M views",
    },
    {
        title: "This Fighter RUINED His Career By Winning | The Fight Factory",
        thumbnail: "https://i.ytimg.com/vi/cupdRadPNT0/oar2.jpg?sqp=-oaymwEaCJUDENAFSFXyq4qpAwwIARUAAIhCcAHAAQY=&rs=AOn4CLBWUEfEWq9ileCFTu-RwArlolhAuw",
        view: "2.1M views",
    },
    {
        title: "đi tạp hóa gần nhà mà vợ lên đồ như đi du lịch, chồng nói ok, anh sẽ hóa thân thành daddy, #Shorts",
        thumbnail: "https://i.ytimg.com/vi/9HQtt9NgHFI/oar2.jpg?sqp=-oaymwEaCJUDENAFSFXyq4qpAwwIARUAAIhCcAHAAQY=&rs=AOn4CLCxq_59vdNwyVhbbbhARrSiK23g_A",
        view: "321K views",
    },
    {
        title: "Wait! What!?? #fitnessmotivation #bodybuilding #motivation",
        thumbnail: "https://i.ytimg.com/vi/HEQiBjuSUQE/oar2.jpg?sqp=-oaymwEaCJUDENAFSFXyq4qpAwwIARUAAIhCcAHAAQY=&rs=AOn4CLD5TMX3RBrUY9prqlsaM9-HGnmokA",
        view: "13M views",
    },
    {
        title: "If you laugh, you restart pt 120",
        thumbnail: "https://i.ytimg.com/vi/cwIcMB-rm0g/hq720.jpg?sqp=-oaymwEdCJUDENAFSFXyq4qpAw8IARUAAIhCcAHAAQbQAQE=&rs=AOn4CLBPZUQIgu0m-yDzbxqYf6bin-AOLA",
        view: "1.5M views",
    },
    {
        title: "Người hướng nội luyện nói T.Anh belike | MinhMinhMinh #Shorts",
        thumbnail: "https://i.ytimg.com/vi/OAJoARTlcrk/oar2.jpg?sqp=-oaymwEaCJUDENAFSFXyq4qpAwwIARUAAIhCcAHAAQY=&rs=AOn4CLD9bVrkn55U_W4586vXJlGEJJYfqQ",
        view: "27K views",
    },
    {
        title: "When my wife watch JungKook's music video for the first time?(Jung Kook-Seven feat. Latto) #shorts",
        thumbnail: "https://i.ytimg.com/vi/fM-VpJs5t7Y/hq720.jpg?sqp=-oaymwEdCJUDENAFSFXyq4qpAw8IARUAAIhCcAHAAQbQAQE=&rs=AOn4CLAhXJdHFUtnFzOxutCFznWFV26DZg",
        view: "7.6M views",
    },
    {
        title: "Crazy shredded arms",
        thumbnail: "https://i.ytimg.com/vi/BXHILqIWcT4/hq720.jpg?sqp=-oaymwEdCJUDENAFSFXyq4qpAw8IARUAAIhCcAHAAQbQAQE=&rs=AOn4CLB0vAt97a89_1t2eryR02x7Th4K5A",
        view: "1.2M views",
    },
    {
        title: "WONDER WOMAN SAVES PRINCESS AUDREY | #animated #justiceleague #batman #wonderwoman #brucewayne #edit",
        thumbnail: "https://i.ytimg.com/vi/jtQXuthExTo/hq720.jpg?sqp=-oaymwEdCJUDENAFSFXyq4qpAw8IARUAAIhCcAHAAQbQAQE=&rs=AOn4CLAZco3Nb_Jqzs3WSUw8a5LFKa2YAQ",
        view: "3.6M views",
    },
]